### ISSUE TITLE
Make height of editor adjustable

### ISSUE THREAD

**Issue by twiro** [animaux/simplemde#1]
The editor currently always has the same default height, no matter what the value of `Number of default rows` in the text field's settings is. Would be great if the height could adapt to that setting.

**Comment by animaux** [comment]
Hmn, Editor for Symphony did ignore that as well. We’re able to add a minimum height via CSS before it grows. I guess that could be translated. Will have a look.

**Comment by animaux** [comment]
I’d rather ignore the field settings and start from a basic smaller height of about 1–3 lines. Since we’re growing with each row this seems more logical for me than to have an however large empty field from the start.

**Comment by animaux** [comment]
Initial height is now 1 line. I consider this fixed :)

**Comment by twiro** [comment]
> _I’d rather ignore the field settings and start from a basic smaller height of about 1–3 lines. Since we’re growing with each row this seems more logical for me than to have an however large empty field from the start._

Having the ability to define a minimum height via settings allows for a cleaner publish layout. Think of two textareas next to each other - looks way better with the same height. I actually use that a lot to structure my publish-area and try to give text-fields a height that won't be extended by its content (which only works for text-areas with somehow restricted amounts of text, but in my experience there are lots of them).

So I don't think it would be a good move to simply ignore the "rows"-settings. If you want a textbox that starts narrow you could simply choose "1" (or even "0") as value in the settings, but I wouldn't force that behavior - it's just taking away a useful opportunity in my eyes.

**Comment by twiro** [comment]
What about a tiny script that grabs the `rows`-attribute from the textfield, calculates a em/rem-based min-height for the editor and injects that in the markup?

**Comment by animaux** [comment]
Ok, fair enough. But this would have to be an option to choose between a fixed height with scroll-bar or a minimum height.

**Comment by animaux** [comment]
I’m open to pull requests :·D

**Comment by twiro** [comment]
> _But this would have to be an option to choose between a fixed height with scroll-bar or a minimum height._

That would even be better. 

> _I’m open to pull requests :·D_

I will give it a try... but that might take some days ;)

**Comment by animaux** [comment]
No hurries :)

**Comment by animaux** [comment]
For reference —> https://github.com/NextStepWebs/simplemde-markdown-editor/#height

**Comment by twiro** [comment]
> _For reference —> https://github.com/NextStepWebs/simplemde-markdown-editor/#height_

Thank you!

What do you think about the following behavior:
- `Number of default rows` =`0`: Field starts with a default (small) height and grows with its content.
- `Number of default rows` > `0`: Field calculates a fixed height based on the row-settings and offers a scrollbar if the content extends the field.

That way we could use the existing settings for the field height to achieve both behaviors. Which on one hand makes sense and on the other might be the most easy and pragmatic solution to implement.

> No hurries :)

...will fork and try as soon as I find the time...

**Comment by animaux** [comment]
Hmn, that would mean I’d have to set all my text-fields to `0` to get the behaviour I want, grrr :)

However making use of the already existing field setting makes sense.

**Comment by twiro** [comment]
Here you go: https://github.com/twiro/simplemde/tree/row-based-editor-height

Looked easy at first glance, but as the dynamic adjustments caused some ugly glitches whilte loading the page I had to rewrite the whole editor initialization. But it's working now and looking good in Firefox, Safari and Chrome...

Besides simply adjusting the height to the row-settings I also tried to keep smaller textareas (up to 10 rows) "in rhythm" with the vertical grid of the symphony backend. And while adjusting paddings and margins I also changed the styling a little bit to make it more in line with the symphony backend. If you're not ok with some of these adjustments I can surely revert them ;)

Have a look and let me know If I should send a PR or if we need to change something!

![simplemde-row-based-editor-height](https://cloud.githubusercontent.com/assets/870227/13883195/aa20961a-ed28-11e5-8dda-243fc5c24660.png)

**Comment by animaux** [comment]
Nice! Will test it on monday and get back to you. Thanks.

**Comment by animaux** [comment]
Looks great to me. Thanks for fixing the repo name too :) Please send a PR!

**Comment by twiro** [comment]
> Looks great to me.

Great - glad you like it :) I added [another small tweak](https://github.com/twiro/simplemde/commit/a4bb2a02bab4bd8c5b589c37036300af3e56e49a) for active elements in the toolbar, but otherwise will submit it the way it was.

> Thanks for fixing the repo name too :)

My pleasure!

> Please send a PR!

Do you wanna set up an `integration`-branch for that? So my PR doesn't automatically become the official master version and we can improve some other details (will post separate issues for them) before releasing a new version?

Regarding releases - I noticed you [didn't use any release-tags](https://github.com/animaux/simplemde/releases) for this extension yet. They're a great feature as they not only make older versions of the extension accessible on github, but also are used for directly linking the version-numbers in the compatibility-table on [symphonyextensions.com](http://symphonyextensions.com/extensions/simplemde/) to the corresponding release on github. Would be cool if you could tag the current master as `0.2` and keep tagging as new versions are released :) (just [getting familiar](https://github.com/twiro/slider/releases) with all that myself...)

**Comment by animaux** [comment]
Thanks! I’m still a github noob :·) Version tags are definitely good to have! 

Have to read a bit about branches before I can handle them. I’d be ok if you PR this into master for now.

**Comment by twiro** [comment]
>  I’d be ok if you PR this into master for now.

Alright - so I'll also update the meta with a new version `0.3` so it'll be a complete and release-ready PR.

We don't have to solve the font question now (https://github.com/animaux/simplemde/issues/4) but it would be cool if you could give me feedback on my screenshot-question: https://github.com/animaux/simplemde/issues/5 before I send my PR. Thank you!

**Comment by animaux** [comment]
Done. Go ahead :+1:

**Comment by twiro** [comment]
> Done. Go ahead :+1:

Cool... [PR](https://github.com/animaux/simplemde/pull/6) is on it's way... hope I didn't miss anything!

**Comment by animaux** [comment]
Fixed in https://github.com/animaux/simplemde/tree/0.3
