### ISSUE TITLE
1.x releases not listed on Github

### ISSUE THREAD

**Issue by cylkee** [animaux/simplemde#11]
Github says latest release is 0.4.4 from 2017 https://github.com/animaux/simplemde/releases

http://symphonyextensions.com/extensions/simplemde/ says latest release is 1.0.2

Got 1.0.3 from a git clone 😜

**Comment by animaux** [comment]
Sorry, I’m not taking releases seriously `;)`

**Comment by animaux** [comment]
Just thought I could update the simplemde-lib itself, but apparently is is still the lastest version … it works.

**Comment by cylkee** [comment]
Thank you.

**Comment by animaux** [comment]
No Problem!
