### ISSUE TITLE
Use the default font instead of a monospace one?

### ISSUE THREAD

**Issue by twiro** [animaux/simplemde#4]
Is there a reason you chose a monospace font family for the editor or does this simply come from the default codemirror styles?

As in most cases the editor will be used to format "regular" text content (meaning: "not code") I would prefer to simply stay with Symphony*s default choice of type - that would also fix the problem, that (especially smaller) bold fonts look quite blurry at the moment:

![screen shot 2016-03-21 at 12 48 59](https://cloud.githubusercontent.com/assets/870227/13918416/7073eff2-ef67-11e5-9530-bb6ed393964d.png)

With your OK I would add that change to my upcoming PR.

**Comment by animaux** [comment]
The reason is I had problems with non-monospace-fonts in the »old« Editor for Symphony. Also as a personal preference I’m inclined to think of markdown text as code. However I’m happy to go back to default symphony if the problems are gone (will check).

**Comment by twiro** [comment]
> The reason is I had problems with non-monospace-fonts in the »old« Editor for Symphony.  However I’m happy to go back to default symphony if the problems are gone (will check).

That would be great - I will also test it more intense in the upcoming days/weeks.

> Also as a personal preference I’m inclined to think of markdown text as code.

Fair enough. I always tend to look at it as both text and code (that's why I love to work with Macdown) but from a client point of view I don't think the "coding" look is of any help.
But it's your extension, I don't wanna push it into a direction you're not happy with!

For the time beeing I changed the css font stack a little bit, so I can at least use an OSX font with a real "bold"-fontweight - avoiding the blurry "faux bold"-effect shown above: https://github.com/twiro/simplemde/commit/25e5554708a2ec38c5a0a499a8c8c7169ae34f78

**Comment by animaux** [comment]
I’m happy to delete the `font-family`line alltogether. Seems to work fine in quick test.

**Comment by twiro** [comment]
> I’m happy to delete the font-familyline alltogether. Seems to work fine in quick test.

That's great to hear - I just updated my branch and sent a PR!

**Comment by animaux** [comment]
Done https://github.com/animaux/simplemde/tree/0.3
