### ISSUE TITLE
Add Screenshot to readme/meta

### ISSUE THREAD

**Issue by twiro** [animaux/simplemde#5]
I cleaned up my "test suite" a little bit and made 2 screenshots that would serve well as example in the repos readme (and meta-file).

Would it be ok for you if I added the monospace version to my upcoming 0.3-PR?

![symphony-cms-simplemde-markdown-editor-1-monospace](https://cloud.githubusercontent.com/assets/870227/13945845/d8e0faa4-f010-11e5-85a8-04ed5bdff0b1.png)

![symphony-cms-simplemde-markdown-editor-1](https://cloud.githubusercontent.com/assets/870227/13945847/d98efd0c-f010-11e5-85f5-bcbe38c930fa.png)

**Comment by animaux** [comment]
Let’s get rid of the monospace-declaration and use the second screenshot it you want :·)

**Comment by twiro** [comment]
> Let’s get rid of the monospace-declaration and use the second screenshot it you want :·)

Second screenshot added - thank you!

**Comment by animaux** [comment]
https://github.com/animaux/simplemde/releases/tag/0.3
